startupproject/startupapp/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from .views import HomeView, StartUpListView

urlpatterns = [
    url(r'^home/$', HomeView.as_view(), name='home-view'),
    url(r'^startups/$', StartUpListView.as_view(), name='startup-list'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

startupproject/startupproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('startupapp.urls'))
]

startupproject/startupapp/models.py
import django.contrib.auth.models
from django.db import models
from django.contrib.postgres.fields import ArrayField


class TypeOfUser(models.Model):
    """Defines the type of an user."""
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Region(models.Model):
    """Defines the region of the startup or an user."""
    name = models.CharField(max_length=512)

    def __str__(self):
        return self.name


class User(models.Model):
    """Defines the user.

    User's image can be null.

    An user can have one or more emails and phones.
    Usually, it is not necessary to have multiple emails,
    so the system can check multiplicity.
    Leave it for the scalability in the future.

    """

    login = models.CharField(max_length=64)
    password = models.CharField(max_length=64)
    first_name = models.CharField(max_length=64)
    middle_name = models.CharField(max_length=64, null=True)
    last_name = models.CharField(max_length=64)
    type = models.ForeignKey(TypeOfUser, on_delete=models.PROTECT)
    region = models.ForeignKey(Region, on_delete=models.PROTECT)
    user_image = models.ImageField(null=True)
    register_date = models.DateTimeField()
    emails = ArrayField(models.CharField(max_length=128))
    phones = ArrayField(models.CharField(max_length=64))
    money_in_rubles = models.DecimalField(decimal_places=2,
                                          default=0,
                                          max_digits=9)

    def __str__(self):
        return self.login


class UserLoginHistory(models.Model):
    """Defines the user login history.

    Must have IPv4 or IPv6 ip address,
    and must say if the login was successful
    at the given datetime.

    """
    is_success = models.BooleanField()
    ip_address = models.GenericIPAddressField()
    login_datetime = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.login_datetime


class Category(models.Model):
    """Defines the category of a startup."""
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class StartUp(models.Model):
    """Defines the startup.

    StartUp must have at least one creator.

    If the first creator assigns the rights
    to the another creator,
    another creator yields ability to delete
    the current startup, so we need password
    checking of the original creator.

    Must have description, otherwise it is impossible
    to identify what is the purpose of the startup.

    Can have zero or one hashtags. They act like categories,
    but more precise.

    """
    name = models.CharField(max_length=128)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    is_actual = models.BooleanField()
    creation_datetime = models.DateTimeField()
    description = models.CharField(max_length=2048)
    max_members_count = models.SmallIntegerField()

    def __str__(self):
        return f'{self.name}.{self.creation_datetime}'


class TypeOfTransaction(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class UserStartupInvestHistory(models.Model):
    """Defines the startups investment history of the user."""

    user = models.ForeignKey(User, on_delete=models.PROTECT)
    startup = models.ForeignKey(StartUp, on_delete=models.PROTECT)
    invest_type = models.ForeignKey(TypeOfTransaction,
                                    on_delete=models.PROTECT)
    invest_datetime = models.DateTimeField()
    invested_money = models.DecimalField(max_digits=9,
                                         decimal_places=2)

    def __str__(self):
        return f'{self.user.login}.' \
               f'{self.invest_type.name}.' \
               f'{self.invest_datetime}'


class StartUpComment(models.Model):
    """Defines the comment of the startup."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=2048)
    post_datetime = models.DateTimeField()
    startup = models.ForeignKey(StartUp, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.login} ({self.post_datetime}):{self.text}'


class StartUpImage(models.Model):
    """Defines the image set of the startup."""
    startup = models.ForeignKey(StartUp, on_delete=models.CASCADE)
    image_title = models.CharField(max_length=64)
    image_description = models.CharField(max_length=2048)
    upload_datetime = models.DateTimeField()
    image_blob = models.ImageField(upload_to='images/')
    user = models.ForeignKey(User,
                             on_delete=models.SET_NULL,
                             null=True)

    def __str__(self):
        return f'{self.user}:{self.image_title}'


class RoleOfStartUp(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class StartUpOfUser(models.Model):
    """Defines the user's role in the startup."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    startup = models.ForeignKey(StartUp, on_delete=models.CASCADE)
    role = models.ForeignKey(RoleOfStartUp, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.login}, {self.startup.name}, {self.role.name}'


class HashTag(models.Model):
    """Defines the set of hashtags for startups."""
    text = models.CharField(max_length=32)
    startups = models.ManyToManyField(StartUp)

    def __str__(self):
        return self.text

startupproject/startupapp/views.py
from .models import StartUp
from django.views.generic import ListView, TemplateView


class StartUpListView(ListView):
    model = StartUp


class HomeView(TemplateView):
    template_name = 'startupapp/home.html'

startupproject/startupapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
{% include 'navbar.html' %}
<body>
{% block content %}
{% endblock %}
{% include 'footer.html' %}
</body>
</html>

startupproject/startupapp/templates/footer.html
<footer class="bg-dark bottom-50 text-light">
    <div class="container ps-4 pe-4 pt-5 pb-5">
        <div class="row">
            <div class="col-md-4 col-sm-12">
                <h5>О сайте</h5>
                <ul class="list-unstyled text-small">
                    <li>
                        <a>
                            Наши контакты
                        </a>
                    </li>
                    <li>
                        <a>
                            О проекте
                        </a>
                    </li>
                    <li>
                        <a>
                            Связаться с нами
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-12">
                <h5>Навигация по сайту</h5>
                <ul class="list-unstyled text-small">
                    <li>
                        <a>
                            Стартапы
                        </a>
                    </li>
                    <li>
                        <a>
                            Личный кабинет
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-12">
                <h5>Мои платежи</h5>
                <ul class="list-unstyled text-small">
                    <li>
                        <a>
                            История инвестирования
                        </a>
                    </li>
                    <li>
                        <a>
                            Пополнить баланс
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

startupproject/startupapp/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'icons/startupapp-logo.svg' %}" alt="" height="50"/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Включить навигацию">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#">Стартапы</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        О сайте
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Наши контакты</a></li>
                        <li><a class="dropdown-item" href="#">О проекте</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Связаться с нами</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Стартапы, инвесторы" aria-label="Поиск">
                <button class="btn btn-outline-light" type="submit">Искать</button>
            </form>
        </div>
    </div>
</nav>

startupproject/startupapp/templates/startupapp/home.html
{% extends 'base.html' %}

{% block title %}Домашняя страница{% endblock %}

{% block content %}
Test
{% endblock %}

startupproject/startupapp/templates/startupapp/startup_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="d-flex flex-wrap justify-content-center m-2">
    {% for startup in startup_list %}
    <div class="container bg-light m-2 rounded-3"
         style="width:400px; height:400px;">
        {% if startup.startupimage_set.count > 0 %}
        {% with startup.startupimage_set.all|first as image %}
        <img alt="Изображение стартапа"
             src="{{ image.image_blob.url }}"
             class="w-100"/>
        {% endwith %}
        {% else %}
        <img alt="Изображение стартапа"
             src="{% static 'icons/no-startup-image.jpg' %}"
             class="w-100"/>
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <p class="fs-3 fw-bold text-center mt-4">
                        {{startup.name}}
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}